baseURL = "https://lunaembedded.com/"
languageCode = "en"
publishDir = "docs"
theme = "lunaembedded"
title = "LUNAEmbedded"

[params]
	authorName = "Alfonso Luna"
	description = "Learn modern embedded systems development"
	avatar = "https://avatars1.githubusercontent.com/u/10271168"
	twitterProfile = "https://twitter.com/AlfonsoJLuna"
	instagramProfile = ""
	githubProfile = "https://github.com/AlfonsoJLuna"
	youtubeProfile = "https://www.youtube.com/channel/UCeMzdV89IlbByrYXtOXnoEA"
	linkedinProfile = ""
	tindieProfile = "https://www.tindie.com/stores/lunaembedded/"
	email = ""

[taxonomies]
	post = "posts"
