baseURL = "https://alfonsoluna.io/"
languageCode = "en"
publishDir = "docs"
theme = "mytheme"
title = "alfonsoluna.io"

[params]
	authorName = "Alfonso Luna"
	avatar = "https://avatars1.githubusercontent.com/u/10271168"
	twitterProfile = "https://twitter.com/AlfonsoJLuna"
	githubProfile = "https://github.com/AlfonsoJLuna"
	youtubeProfile = "https://www.youtube.com/channel/UCeMzdV89IlbByrYXtOXnoEA"
	linkedinProfile = "https://www.linkedin.com/in/alfonsojluna/"
	tindieProfile = "https://www.tindie.com/stores/alfonsojluna/"

[taxonomies]
	post = "posts"
